### ISSUE TITLE
NPM Error

### ISSUE THREAD

**Issue by swbam** [alexodle/golfdraft#7]
When I try and start this with the instructions given I get the error below. Is there any way you could make a more in-depth guide on how to get this running? I would really appreciate it. 

`npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/USERNAME/.npm/_logs/2020-03-09T19_50_42_704Z-debug.log
USERNAME's-New-Macbook-Pro:golfdraft USERNAME$ npm start

> golfdraft-react-flux@ start /Users/USERNAME/golfdraft
> node tsDist/server/server.js

internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module '/Users/USERNAME/golfdraft/tsDist/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! golfdraft-react-flux@ start: `node tsDist/server/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the golfdraft-react-flux@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/USERNAME/.npm/_logs/2020-03-09T19_51_06_837Z-debug.log`

**Comment by alexodle** [comment]
Hey @swbam. These directions fell out of sync a bit ago, and I haven't been able to fully vet them as I'm the only one using this really using this repo. I believe the directions to get this running locally are:

```
npm install && npm run buildServer && npm run run:dev
```

Let me know if that doesn't work.
